### ISSUE TITLE
Setup failed for deebot: No setup function defined

### ISSUE THREAD

**Issue by cagnulein** [And3rsL/Deebot-for-hassio#16]
I'm installing it but when i restart Home Assistant it gives me this error on the log: Setup failed for deebot: No setup function defined

I'm installing it from HACS. Any ideas? I've tried also version 1.4 of your repo but it gives me the same error

**Comment by elmurato** [comment]
@cagnulein Did you add it to the configuration as shown in the README?

```
vacuum:
  - platform: deebot
    username: YOUR_ECOVACS_USERNAME
    password: YOUR_ECOVACS_PASSWORD
    country: YOUR_TWO_LETTER_COUNTRY_CODE
    continent: YOUR_TWO_LETTER_CONTINENT_CODE
    deviceid: YOUR_ROBOT_ID
```
