### ISSUE TITLE
Integration 'deebotozmo' not found

### ISSUE THREAD

**Issue by bigdaddy5414** [And3rsL/Deebot-for-hassio#24]
I get this error when checking config with this add-on installed, Platform error vacuum.deebotozmo - Integration 'deebotozmo' not found.

Home Assistant 0.110.3
HassOS 3.13

**Comment by And3rsL** [comment]
Did you install it via HACS?

Can you share your configuration inside configuration.yaml?
it should look like this:

```
vacuum:
  - platform: deebot
    username: YOUR_ECOVACS_USERNAME
    password: YOUR_ECOVACS_PASSWORD
    country: YOUR_TWO_LETTER_COUNTRY_CODE
    continent: YOUR_TWO_LETTER_CONTINENT_CODE
    deviceid: YOUR_ROBOT_ID
    livemappath: 'www/live_map.png'
```
