### ISSUE TITLE
NEW ISSUES

### ISSUE THREAD

**Issue by And3rsL** [And3rsL/Deebot-for-hassio#29]
## PLEASE CHECK IF THERE IS ALREDY A ISSUE BEFORE OPEN A NEW ONE
I closed older issues, all issues posted WITHOUT the following template will be closed and ignored

## TEMPLATE:

**Describe the bug**

**Configuration.yaml (Remember to delete your credentials)**
```
vacuum:
  - platform: deebot
    username: YOUR_ECOVACS_USERNAME
    password: YOUR_ECOVACS_PASSWORD
    country: YOUR_TWO_LETTER_COUNTRY_CODE
    continent: YOUR_TWO_LETTER_CONTINENT_CODE
    deviceid: YOUR_ROBOT_ID
```

**Screenshots**

**System Informations:**
 - Device: [Deebot ozmo 950][.. 960][.. 920]
 - Home Assistant Version: 0.110.0 ...
 - Hardware: Raspberry,NAS, etc..
 - Home Assistant Installation: Windows/Linux

**Additional context**

**Logs**
Please add full home_assistant.log filtered on [deebotozmo]
