### ISSUE TITLE
Status of Deebot is always "docked"

### ISSUE THREAD

**Issue by bkvargyas** [And3rsL/Deebot-for-Hassio#31]
The plugin always shows the bot is docked, even if the deebot is in auto-clean mode cleaning on a schedule from the deebot app.   However, battery level is reported correctly.   If you tell deebot to clean from this plug-in, then status is reported correctly. 

**Configuration.yaml (Remember to delete your credentials)**

vacuum:
  - platform: deebot
    username: !username
    password: !password
    country: US
    continent: NA
    deviceid: E03307511B09HCBP0130
    # Optional
    live_map: True                    # Enable Live Map.. may cause issues on low power hardware | 
    Default: True
    show_color_rooms: False           # Enable draw room colors as in the app | Default: False
    livemappath: 'www/live_map.png'   # Path where to save live_map

![image](https://user-images.githubusercontent.com/8314737/84920318-9cbe9d00-b088-11ea-9f05-90bc90f6c142.png)

**System Informations:**
 - Device: Deebot 920
 - Home Assistant Version: 0.111.2 ...
 - Hardware: ESXI vmware x86
 - Home Assistant Installation: hass.io

**Additional context**

**Logs**
no log information was generated with deebot in the name.

**Comment by And3rsL** [comment]
please increse level of logs in hassio and report log here

in configuration.yaml add 
logger:
  default: debug

**Comment by Nusse469** [comment]
I have the same problem. But only on the T8. I have a 920 that runs and displays status accurately.

**Comment by mariobarisic** [comment]
I can confirm with my configuration:
    Device: Deebot T8 - FW 1.6.3
    Home Assistant Version: 2021.1.1
    Hardware: Rpi4

and with latest addon update I'm still getting status for my vacuum - docked while cleaning is active (scheduled one from ECOVACS mobile app). Other attributes under vacuum.robot_name are regularly updated while cleaning (or scrubbing) is in progress and also other sensors within this integration.

**Comment by Nusse469** [comment]
I thought I was fixed as well but that only lasted for a short time.   My T8 shows as "docked" all the time and the 920 works fine like in my previous post.

**Comment by mariobarisic** [comment]
I just wan't to give as much information regarding this "bug". As I can see it's only present when the robot starts to clean via scheduled job within mobile app. If I start spot cleaning or automatic cleaning from mobile application robot status is updated to cleaning.
My configuration is as follows:

```
deebot:
  username: !secret deebot_user
  password: !secret deebot_pass
  country: HR
  continent: EU
  deviceid: !secret deebot_id
  # Optional
  live_map: True                    # Enable Live Map.. may cause issues on low power hardware | Default: True
  show_color_rooms: False          # Enable draw room colors as in the app | Default: False
  livemappath: 'www/deebot/'   # Path where to save live_map (Each bot will have XXX.png where XXX is the vacbot name)
```
System informations:
```
Device: Deebot T8
Home Assistant Version: 2021.1.4
Integration: Deebot for Hassio v.1.9.8.
Hardware: Rpi4 4GB
Home Assistant Installation: hass.io
```
So during scheduled job, robot remains Docked:
![image](https://user-images.githubusercontent.com/60128241/105041470-53419080-5a63-11eb-9dbd-8ea000ec760b.png)
![image](https://user-images.githubusercontent.com/60128241/105041573-70765f00-5a63-11eb-8686-819bce0c8cff.png)

while battery status and other sensors are updated:
![image](https://user-images.githubusercontent.com/60128241/105041591-7704d680-5a63-11eb-98b3-4263472a0eff.png)
![image](https://user-images.githubusercontent.com/60128241/105041611-7e2be480-5a63-11eb-85f7-0b4a3c70b7f5.png)

I have activated logs in HA, but in this moment I don't have any to post here. I will try later to initiate another scheduled job within the app and then updated my post with relevant logs.

**Comment by Yterz** [comment]
I have that issue too. Status is updated when something is controlled from HA or Ecovacs app, but doesn't change when Ecovacs app's schedule trigger
Config :
```
deebot:
  username: Exxxxxx
  password: ********
  country: cn
  continent: ww
  deviceid:
    - 1234567890ABCDE
  live_map: True
  show_color_rooms: False # Not showing color + not refreshing image anymore if set to True
  livemappath: 'www/' # I had to create the folder config/www/

camera:
  - platform: generic
    name: Deebot_live_map
    still_image_url: "https://192.168.1.10:8123/local/DeebYterz_liveMap.png" # DeebYterz being the name of my vacuum in Ecovacs app
    verify_ssl: false
```

Test I made, with the corresponding History & Logbook from HA :
- From HA (blue) : 7:37 start, 7:38 pause, 7:38 resume, 7:39 go dock (status = cleaning when he return to dock). 7:40 he's at dock. No status issue.
- From HA again(blue): same, from 7:42 to 7:44. No status issue.
- From Ecovacs app (green) : 7:46 start, 7:48 go dock. 7:49 he's at dock. No status issue.
- From Ecovacs app (green) : I set a schedule for 7:51. Robot start cleaning at 7:51, but HA status doesn't change to Cleaning, it's stuck on docked, and the map update its position. Ecovacs app do acknowledge the status change.
   7:54 I hit pause on the app, robot pause, HA status update from Docked to Paused.
   7:55 I hit go dock on the app, robot go dock, HA status update to Cleaning (it returning dock status, as before).

So the only status update HA missed is really the schedule trigger. Anything else is properly recorded.

<img width="967" alt="History" src="https://user-images.githubusercontent.com/73762135/106515646-4480c200-64d6-11eb-9ea5-6bb3fa335b3a.png">
<img width="454" alt="Logbook" src="https://user-images.githubusercontent.com/73762135/106515655-48144900-64d6-11eb-8248-4f78a1d3af5b.png">

I'll send you the full HA log by PM, I have no idea how to properly clean that from sensitive data...
```
logger:
  logs:
    homeassistant.components.deebot: debug
    homeassistant.components.vacuum.deebotozmo: debug
    deebotozmo: debug
```

**Comment by Yterz** [comment]
But I already replaced the Ecovacs Schedule with a HA one, more customizable. If interested here's the basic of it that you can copy/past in an automation (I added absence & guess switch off condition to mine) :

```
alias: 'Deebot Schedule '
description: Schedule for my vacuum
trigger:
  - platform: time
    at: '14:00:00' #Change trigger time to your convenience
condition:
  - condition: time
    weekday: #Change weekday it's allowed to trigger to your convenience
      - mon
      - fri
action:
  - service: vacuum.start
    data:
      entity_id: vacuum.deebyterz #Edit entity_id with your vacuum
mode: single

```
