### ISSUE TITLE
Auth failed: incorrect email or password

### ISSUE THREAD

**Issue by edenhaus** [And3rsL/Deebot-for-hassio#36]
**Describe the bug**
I cannot login with my credentials (for ecovacs) using your custom component. I always get incorrect email or password.
The credentials are correct as I can login with the same credentials using debootozmo directly on my personal laptop (Ubuntu 20.04).
I found the following out, when debugging and comparing debootozmo (running it locally) with Home Assistant (remote debugging  with debugpy):
- account_id and password_hash are the same
- `self.encrypt`returns different values (compared to the local running version) (debootozmo/init.py:51)
  ```
  login_info = self.__call_main_api('user/login',
                                          ('account', self.encrypt(account_id)),
                                          ('password', self.encrypt(password_hash)))
  ```
- When I copy the encrypted account_id and password_hash from the local running debootozmo to the HA running instance, I can login successfully. So I think there is a problem with the method `self.encrypt` or probably with the underlying cryptodome. 

**Configuration.yaml (Remember to delete your credentials)**
```
vacuum:
  - platform: deebot
    username: !secret ecovacs_mail
    password: !secret ecovacs_pass
    country: it
    continent: eu
    deviceid: !secret ecovacs_susi_id
    # Optional
    live_map: True # Enable Live Map.. | Default: True
    show_color_rooms: True # Enable draw room colors as in the app | Default: False
    livemappath: "www/susi_live_map.png" # Path where to save live_map
```

**System Informations:**
 - Device: Deebot ozmo 950
 - Home Assistant Version: 0.113.0 ...
 - Hardware: Desktop PC with Ubuntu Server 20.04
 - Home Assistant Installation: Docker Core Installation

**Additional context**

**Logs**
Please add full home_assistant.log filtered on [deebotozmo]
```
home-assistant_1  | 2020-07-24 16:30:55 DEBUG (SyncWorker_6) [deebotozmo] Setting up EcoVacsAPI
home-assistant_1  | 2020-07-24 16:30:55 DEBUG (SyncWorker_6) [deebotozmo] calling main api user/login with (('account', 'REMOVED'), ('password', 'REMOVED'))
home-assistant_1  | 2020-07-24 16:30:56 DEBUG (SyncWorker_6) [deebotozmo] got {'code': '1005', 'msg': '当前密码错误', 'time': 1595601055850, 'data': None}
home-assistant_1  | 2020-07-24 16:30:56 WARNING (SyncWorker_6) [deebotozmo] incorrect email or password

```
