### ISSUE TITLE
Error [username] is an invalid option for [vacuum.deebot]

### ISSUE THREAD

**Issue by magicdude4eva** [And3rsL/Deebot-for-hassio#45]
**Describe the bug**
Updated to latest version of plugin and received the error "[username] is an invalid option for [vacuum.deebot]" after restart and core-check.

**Configuration.yaml (Remember to delete your credentials)**
```
via include:
vacuum: !include includes/vacuum.yaml

and then in includes/vacuum.yaml:

- platform: deebot
  username: REDACTED
  password: REDACTED
  country: AT
  continent: EU
  deviceid: REDACTED
  # Optional
  live_map: True
  show_color_rooms: False
  livemappath: 'www/live_map.png'
  verify_ssl: false

```

**Logs**
~ $ ha core check
Processing... Done.

Error: Testing configuration at /config
INFO:homeassistant.util.package:Attempting install of deebotozmo==1.6.8
Failed config
  vacuum.deebot:
    - Invalid config for [vacuum.deebot]: [username] is an invalid option for [vacuum.deebot]. Check: vacuum.deebot->username. (See ?, line ?).
    - platform: deebot
      continent: EU
      country: AT
      deviceid: REDACTED
      live_map: True
      livemappath: www/live_map.png
      password: REDACTED
      show_color_rooms: False
      username: REDACTED
      verify_ssl: False
Successful config (partial)
  vacuum.deebot:

**Comment by Vorms** [comment]
same issue here

**Comment by edenhaus** [comment]
In the last version was a breaking change. (See https://github.com/And3rsL/Deebot-for-hassio/releases/tag/1.9.5)

You must adopt your config. The new config schema looks like:
```
deebot:
  username: !secret ecovacs_mail
  password: !secret ecovacs_pass
  country: it
  continent: eu
  deviceid: !secret ecovacs_susi_id
  # Optional
  live_map: true # Enable Live Map..
  show_color_rooms: true # Enable draw room colors as in the app
  livemappath: "www/susi_live_map.png" # Path where to save live_map
```
