### ISSUE TITLE
Update to latest version excludes Ozmo950 room details

### ISSUE THREAD

**Issue by magicdude4eva** [And3rsL/Deebot-for-hassio#51]
**Describe the bug**
The previous versions included the room Ids. The updated integration does not deliver those attributes:

```
fan_speed_list:
  - quiet
  - normal
  - max
  - max+
battery_level: 100
battery_icon: 'mdi:battery'
fan_speed: max
friendly_name: Deedee
supported_features: 13172
```

**Screenshots**
I do see the rooms as sensors:
![image](https://user-images.githubusercontent.com/1632781/97912842-ad2c9700-1d4d-11eb-87cd-5e1439e01456.png)

How do I reference those in scripts 
```
        - name: 'Clean Lounge'
          icon: 'mdi:sofa'
          service: script.vacuum_clean_spot_area
          service_data:
            cleaning_area_rooms: '25'
            cleaning_area_alias: "Clean Lounge"
            cleaning_device_name: vacuum.deedee

```

**System Informations:**
 - Device: Deebot ozmo 950
 - Home Assistant Version: 2020.10.1
 - Hardware: Raspberry PI4 / HassOS 4.15
 - Home Assistant Installation: Linux
