### ISSUE TITLE
T8 AIVI integration not working with 1.9.5/1.9.6/1.9.7

### ISSUE THREAD

**Issue by cubilon** [And3rsL/Deebot-for-hassio#61]
**Describe the bug**
While with 1.9.4 the integration worked (and works) like a charm, with 1.9.7 stopped working.
Tried 1.9.5, 1.9.6, same error (see below).

**Configuration.yaml (Remember to delete your credentials)**
```
vacuum:
  - platform: deebot
    username: XXXX@XXXX.com
    password: XXXXXXX
    country: it
    continent: eu
    deviceid: EXXXXXXXXXXX
    # Optional
    #live_map: True
    #show_color_rooms: False
    #livemappath: 'www/live_map.png'
```

**Screenshots**
<a href="https://ibb.co/gZrQ14v"><img src="https://i.ibb.co/PGrJpDT/Screenshot-2020-11-16-at-16-07-45.png" alt="Screenshot-2020-11-16-at-16-07-45" border="0"></a>

**System Informations:**
 - Device: T8 AIVI
 - Home Assistant Version: 0.117.6
 - Hardware: Raspberry
 - Home Assistant Installation: Core on venv (on Raspbian)
