### ISSUE TITLE
Multiple floor support

### ISSUE THREAD

**Issue by marioedani** [And3rsL/Deebot-for-hassio#72]
**Describe the bug**
I own a 2 floors house. In Ecovacs app I have 2 maps, one per floor.
When I move vacuum cleaner from one floor to the other Android app recognizes map accordingly, while attributes of the vacuum entity in home assistant DON'T change. It seems component ignores second floor areas/rooms.

**Configuration.yaml**
```
deebot:
    username: !secret deebot_username
    password: !secret deebot_password
    country: IT
    continent: EU
    deviceid:
    - E0xxxxxxxxxxxxxxxxxx
    live_map: True
    show_color_rooms: False
    livemappath: 'www/'
```

**Screenshots**

**System Informations:**
Device: Deebot ozmo 920
Home Assistant Version: 2020.12.3
Hardware: Raspberry
Home Assistant Installation: Linux wt Supervisor

**Additional context**
Attributes:
```
fan_speed_list:
  - quiet
  - normal
  - max
  - max+
battery_level: 100
battery_icon: 'mdi:battery'
fan_speed: normal
room_dining_room: 0
room_kitchen: 1
room_living_room: 6
room_laundry: 3
room_storeroom: 4
friendly_name: Robottino
supported_features: 13172
```

**Logs**
No error
