### ISSUE TITLE
Support for multiple account

### ISSUE THREAD

**Issue by Edo78** [And3rsL/Deebot-for-Hassio#77]
My first deebot was a chinese one so I had to use a chinese account then I bought another deebot (a global one) so I created an italian account.

Sadly I can't find a way to use multiple accounts at once.
If I use multiple `deebot` integration the latest override everything and only that account works.
If I try
```
deebot:
  - username: YOUR_ECOVACS_USERNAME
    password: YOUR_ECOVACS_PASSWORD
    country: YOUR_TWO_LETTER_COUNTRY_CODE
    continent: YOUR_TWO_LETTER_CONTINENT_CODE
    deviceid:
      - YOUR_ROBOT_ID
  - username: YOUR_ECOVACS_USERNAME
    password: YOUR_ECOVACS_PASSWORD
    country: YOUR_TWO_LETTER_COUNTRY_CODE
    continent: YOUR_TWO_LETTER_CONTINENT_CODE
    deviceid:
      - YOUR_ROBOT_ID
```
I get an error
```
Invalid config for [deebot]: expected a dictionary for dictionary value @ data['deebot']. Got [OrderedDict([('username', 'XXXXXXXX'), ('password', 'XXXXXX'), ('country', 'CN'), ('continent', 'ww'), ('deviceid', ['XXXXXXXXXXXXX'])]), OrderedDict([('username', 'XXXXXXXX'), ('password', 'XXXXXX'), ('country', 'IT'), ('continent', 'EU'), ('deviceid', ['XXXXXXXXXXXXX'])])]. (See /config/configuration.yaml, line 67).
```
