### ISSUE TITLE
get dynamically room numbers if multiple

### ISSUE THREAD

**Issue by tcarlsen** [And3rsL/Deebot-for-hassio#81]
I like the idea of getting the room numbers dynamically for a script. but what if I have multiple room_kids_room?

```
command: spot_area
params:
  rooms: {{ states.vacuum.ozmo.attributes. room_kids_room }}
  cleanings: 1
```

This returns rooms in an array and not a string:

```
command: spot_area
params:
  rooms:  [1, 3]
  cleanings:
```
