### ISSUE TITLE
Service vacuum.send_command with command: clean and type: auto not working

### ISSUE THREAD

**Issue by KC-inDomus** [And3rsL/Deebot-for-hassio#87]
Got Home Assistant 2021.2.3 with Deebot for Hassio 2.0.1.

Trying execute something like this on my working integrated T8 AIVI:

```
      - service: vacuum.send_command
        entity_id: vacuum.ecovacs_t8_aivi
        command: clean
        params:
          type: auto
```

Seems not working. If inserted on a script, loading the scripts says  command: clean is not supported.
Other commands (set_water, spot_area etc.) are working fine.
