### ISSUE TITLE
Taking too long to set up

### ISSUE THREAD

**Issue by phoniclynx** [And3rsL/Deebot-for-Hassio#94]
**Describe the bug**
Wlorked out how to set up the device through HACS uaing HASS 2021.3.3 and the plugin fails to set up correctly and gives two warning saying it is taking too long to set up and then does not get set up. 

**Configuration.yaml (Remember to delete your credentials)**
```
# Vacumme cleaner config
deebot:
  username: 
  password: 
  country: au
  continent: eu
  deviceid:
    - E0001206218607710146
  # Optional
  live_map: True
  show_color_rooms: False 
  livemappath: 'www/'
```

**Screenshots**
![image](https://user-images.githubusercontent.com/3883152/110595172-9e5b6280-81cd-11eb-8744-5026961ad771.png)

**System Informations:**
 - Device: [Deebot ozmo [.. 960]
 - Home Assistant Version: 2021.3.3
 - Hardware: Raspberry
 - Home Assistant Installation: RPi

**Logs**
Please add full home_assistant.log filtered on [deebotozmo]
